name: Angular CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'DownloaderModule-Web/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'DownloaderModule-Web/**'

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: DownloaderModule-Web/package-lock.json

    - name: Install dependencies
      run: npm install
      working-directory: DownloaderModule-Web

    - name: Run Angular build
      run: npm run build --if-present
      working-directory: DownloaderModule-Web

    - name: Run Angular tests
      run: npm run test -- --watch=false --browsers=ChromeHeadless
      working-directory: DownloaderModule-Web
