# This workflow will Lint check a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Vulnerability Scan

on:
  push:
    branches: [main]
    paths:
      - 'DownloaderModule/**'
  pull_request:
    branches: [main]
    paths:
      - 'DownloaderModule/**'

jobs:
  security-audit:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: DownloaderModule

      - name: Check for vulnerable packages
        run: dotnet list package --vulnerable
        working-directory: DownloaderModule
