# This workflow will Lint check a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Vulnerability Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-audit:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

<<<<<<< Updated upstream
=======
      - name: Check if .NET files changed
        id: check_changes
        shell: bash
        run: |
          git fetch origin main --depth=1
          CHANGED_FILES=$(git diff --name-only origin/main ${{ github.sha }})
          if echo "$CHANGED_FILES" | grep -E '^(DownloaderModule/.*\.(csproj|sln|props|config|cs)$|\.github/workflows/vulnerability-scan\.ya?ml)$'; then
            echo "run=true" >> $GITHUB_OUTPUT
          else
            echo "run=false" >> $GITHUB_OUTPUT
          fi

>>>>>>> Stashed changes
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: DownloaderModule

      - name: Check for vulnerable packages
        run: dotnet list package --vulnerable
        working-directory: DownloaderModule
